all:
	rdmd -dw -wi --build-only -of=./bin/graph.out main_graph.d
	rdmd -dw -wi --build-only -of=./bin/digraph.out main_digraph.d
	rdmd -dw -wi --build-only -of=./bin/network.out main_network.d

clean:
	$(RM) *.o
